### ISSUE TITLE
Download link in README broken :(

### ISSUE THREAD

**Issue by chrislarsenqlik** [axisgroup/QS-MapboxGL#1]
Hey please check the link for "Download the extension here." in the README.md

Fatal error: require_once(): Failed opening required '/home/axc55/public_html/blog/viz/wp-load.php' (include_path='.:/usr/local/php56/pear') in /home/axc55/public_html/blog/viz/wp-blog-header.php on line 12

**Comment by skokenes** [comment]
Fixed thanks man
