### ISSUE TITLE
Error: Rendering of Visualization went wrong (in German: Rendering der Visualisierung fehlgeschlagen.)

### ISSUE THREAD

**Issue by rehasig** [axisgroup/QS-MapboxGL#2]
Dear skokenes,

your web-demo looks so promising.
Unfortunately I get an error message "Rendering of Visualization went wrong" in the worksheet when I try to visualize some point data that I managed to visualize before with the other Qlik map successfully.
In Qlik Sence I can view the extension Mapbox GL and five features in the property panel:
-     Mapbox Access Token - I entered my Mapbox API-token
-     Circle Color - the color of the circles rendered. Should be a hex color code
-     Circle Opacity - the opacity of the circles
-     Circle Size - the range of size from biggest to smallest circle based on the measure
-     Map Style - I selected "Streets" but the other do not work either
  Don't I have to enter an URL of the Map from Mapbox somewhere?
  Any other tips on what to try to get the visualization or the demo *qvf-file running?

Futher, I cannot open the example demo file (31KB). (Error message translated to English:)"Error occured: App could not be called, because no App was charged." Does it have to be put in a certain path?

For the others: Found out how the download-link for the extenson is correct: http://viz.axisgroup.com/extensions/QS-MapboxGL.zip

Thank you for your efforts

**Comment by skokenes** [comment]
Can you post your app (or an equivalent that contains the chart giving this error) so I can look at it? Thanks

**Comment by rehasig** [comment]
Dear skokenes,

Thank you for your fast respons. Please find enclosed the app. In the worksheet on the left is the simple map that comes with Qlik - on the right is my try with MapBox GL.
[Test_Mapbox_GL.zip](https://github.com/axisgroup/QS-MapboxGL/files/290643/Test_Mapbox_GL.zip)

Thank you so much for taking a look.

Best regards

**Comment by skokenes** [comment]
The app you provided works for me :/

Can you provide some further details like browser, OS, machine? Are you trying this on a VM?

**Comment by rehasig** [comment]
Dear Mr Kokenes

Thank you very much for your fast reply.
I am using Qlik Sense Desktop Version 2.2.4
OS: Windows 7 - 64 bit
No VM - just use it on my desktop in normal way.
I do not understand your question regarding the browser, as I do not use 
the app via web but just on my laptop. Should this not be possible?
Could it be that the *.zip file for the extension was not complete?

When I try to open the MapboxGL Extension.qvf (I believe this was your 
example file) in the Development hub in Firefox-browser I very shortly 
see the error message: No object with IDMU8 ID found

  Best regards
      Regina

Am 31.05.2016 um 18:25 schrieb Speros Kokenes:

**Comment by skokenes** [comment]
I'll have to test further in the Qlik Sense Desktop client. I have only tested via the server. Just curious, when you go to the server demo, does it work for you? The link is http://sense.axisgroup.com/sense/app/6f716fc6-5d15-4315-a6cd-cdfa4f0a2ba8/sheet/PnL/state/analysis

**Comment by rehasig** [comment]
From the link of your demo server it works like a charm.
  Best regards
      Regina

Am 02.06.2016 um 22:57 schrieb Speros Kokenes:

**Comment by skokenes** [comment]
I have found the issue. The Qlik Sense Desktop client does not support WebGL, so this extension cannot work when using the Qlik Sense Desktop client. However, you can still use it in Qlik Sense Desktop if you open Qlik Sense Desktop in a web browser like Chrome. To do that:
1. Open Qlik Sense Desktop
2. While QSD is still open, go to a web browser and navigate to "localhost:4848/hub"
3. Enjoy!
